USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PROJECT_DB DATA_RETENTION_TIME_IN_DAYS = 1 COMMENT = 'Project demo DB';
CREATE SCHEMA IF NOT EXISTS PROJECT_DB.RAW; -- Bronze
CREATE SCHEMA IF NOT EXISTS PROJECT_DB.STAGE; -- Silver
CREATE SCHEMA IF NOT EXISTS PROJECT_DB.CORE; -- Gold

-- lightweight file formats for future COPY / Snowpipe
CREATE FILE FORMAT IF NOT EXISTS PROJECT_DB.PUBLIC.json_format TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE;
CREATE FILE FORMAT IF NOT EXISTS PROJECT_DB.PUBLIC.csv_format TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1;

CREATE STAGE IF NOT EXISTS PROJECT_DB.RAW.INTERNAL_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'PROJECT_DB.PUBLIC.csv_format')
  COMMENT = 'Internal stage for small test files';

SHOW DATABASES LIKE 'PROJECT_DB';
SHOW SCHEMAS IN DATABASE PROJECT_DB;
SHOW FILE FORMATS IN SCHEMA PROJECT_DB.PUBLIC;