CREATE WAREHOUSE IF NOT EXISTS COMPUTE_XSMALL
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60       -- in seconds
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Dev warehouse: small and auto-suspend for cost control';

SHOW WAREHOUSES LIKE 'COMPUTE_%';
-- quick runtime check
SELECT CURRENT_WAREHOUSE();

-- create a small resource monitor (example: 10 credits quota)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROJECT
  WITH CREDIT_QUOTA = 10
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

-- attach monitor to the dev warehouse
ALTER WAREHOUSE COMPUTE_XSMALL SET RESOURCE_MONITOR = RM_PROJECT;

SHOW RESOURCE MONITORS;
