-- grant warehouse & DB usage
GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE DE_DEV;
GRANT USAGE ON DATABASE PROJECT_DB TO ROLE DE_DEV;

-- allow developers to create objects in RAW & STAGE
GRANT CREATE TABLE, CREATE STAGE ON SCHEMA PROJECT_DB.RAW TO ROLE DE_DEV;
GRANT CREATE TABLE ON SCHEMA PROJECT_DB.STAGE TO ROLE DE_DEV;

-- read-only analyst
GRANT USAGE ON DATABASE PROJECT_DB TO ROLE ANALYST_READONLY;
GRANT USAGE ON SCHEMA PROJECT_DB.CORE TO ROLE ANALYST_READONLY;
-- grant SELECT to specific tables/views later, after models exist:
-- GRANT SELECT ON TABLE PROJECT_DB.CORE.METRICS_HOURLY TO ROLE ANALYST_READONLY;
